import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "./globalProvider";
import Header from "@/components/Header";
import QueryProvider from "@/providers/QueryProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Groww Frontend Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        <GlobalProvider>
          <QueryProvider>
            <main>{children}</main>
          </QueryProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
